/**
 * 439 splashes from Minecraft Java Edition
 */
export const je = [
  '...!',
  '.party()!',
  '"Almost never" is an interesting concept!',
  '"Autological" is!',
  '[this splash text is now available]',
  '/give @a hugs 64',
  '#minecraftfarms',
  '<3 Max & 99 & Ducky!',
  '1% sugar!',
  '10 years of Mining and Crafting!',
  '12 herbs and spices!',
  '20 GOTO 10!',
  '90% bug free!',
  '100% pure!',
  '150 bpm for 400000 minutes!',
  '150% hyperbole!',
  '12345 is a bad password!',
  '90210!',
  '4815162342 lines of code!',
  'A riddle, wrapped in a mystery!',
  'A skeleton popped out!',
  'Absolutely fixed relatively broken coordinates',
  'Absolutely no memes!',
  'Afraid of the big, black bat!',
  'Age of Wonders is better!',
  'Ahhhhhh!',
  'All inclusive!',
  'All is full of love!',
  'All rumors are true!',
  'Also try Braid!',
  'Also try Limbo!',
  'Also try Minecraft Dungeons!',
  'Also try Mount And Blade!',
  'Also try Pixeljunk Shooter!',
  'Also try Project Zomboid!',
  'Also try Super Meat Boy!',
  'Also try Terraria!',
  'Also try VVVVVV!',
  'Also try World of Goo!',
  'Amplify and listen to BIPOC voices!',
  'An illusion! What are you hiding?',
  'And my pickaxe!',
  'As seen on TV!',
  'Ask your doctor!',
  'Autonomous!',
  'Awesome community!',
  'Awesome game design right there!',
  'Awesome!',
  'Aww man!',
  'Be anti-racist!',
  'Bees, bees, bees, bees!',
  'Bekarton guards the gate!',
  'Best in class!',
  'Big Pointy Teeth!',
  'Bigger than a bread box!',
  'Black lives matter!',
  'Blue warrior shot the food!',
  'Board game version also available!',
  'Boats FTW',
  'Boots with the fur!',
  'Bread is pain!',
  'Bring it on!',
  'Bring me Ray Cokes!',
  'Bringing home the bacon!',
  'BTAF used to be good!',
  'Buckets of lava!',
  'Bushy eyebrows!',
  'Buzzy Bees!',
  'Call your mother!',
  'Casual gaming!',
  'Check it out!',
  'Check out the far lands!',
  'Classy!',
  'Closed source!',
  'Cloud computing!',
  'Cogito ergo sum!',
  'Collaborate and listen!',
  'Colormatic',
  'Complex cellular automata!',
  'Contains infinite genders!',
  'Contains simulated goats!',
  'Conventional!',
  'Cough or sneeze into your elbow!',
  'Cow Tools!',
  'Create!',
  'Croak team!',
  'Cruising streets for gold!',
  'Cześć Polsko!',
  'Déjà vu! [N 3]',
  'Do it all, everything!',
  'Do not distribute!',
  'Do you want to join my server?',
  'Does barrel rolls!',
  'doot doot',
  'Double buffered!',
  'DRR! DRR! DRR!',
  'Dungeon!',
  'DungeonQuest is unfair!',
  'Edit is a name!',
  'Educate your friends on anti-racism!',
  'Engage!',
  'Enhanced!',
  'Envision! Create! Share!',
  'Eple (original edit)!',
  'Euclidian! [sic]',
  'Everybody do the Leif!',
  'Excitement!',
  'Exclusive!',
  'Exploding creepers!',
  'Extra things!',
  'Fabulous graphics!',
  'Falling off cliffs!',
  'Falling with style!',
  'Fan fiction!',
  'Fantasy!',
  'Fat free!',
  'Feature packed!',
  'Finally complete!',
  'Finally with ladders!',
  'Find your claw!',
  'Finger-licking!',
  'Flashing letters!',
  'Flavor with no seasoning!',
  'Flaxkikare!',
  'Flower forest TM perfume',
  'Fnord!',
  'Follow the train, CJ!',
  'Freaky!',
  'Free dental!',
  'From free range developers!',
  'From the streets of Södermalm!',
  'Full of stars!',
  'Funk soul brother!',
  'FUNKY LOL',
  'Gamers unite - separately in your own homes!',
  'Gargamel plays it!',
  'Gasp!',
  'Get to the coppah!',
  'Ghoughpteighbteau tchoghs!',
  'Give us Gordon!',
  'GNU Terry Pratchett',
  'Go to the dentist!',
  'Google anlyticsed!',
  'Got your nose!',
  'GOTY!',
  'Guaranteed!',
  'Haha, LOL!',
  'Haley loves Elan!',
  'Hampsterdance!',
  'Han shot first!',
  'Hang out with your friends online!',
  'Hard to label!',
  'Has an ending!',
  'Hat Fridays!',
  'Haunted!',
  'Heaps of hits on YouTube!',
  'Helo Cymru!',
  'Herregud!',
  'Holy cow, man!',
  'Home-made!',
  'Homeomorphic to a 3-sphere!',
  'Honey, I grew the bees!',
  'Honey, I waxed the copper!',
  'Hot tamale, hot hot tamale!',
  'Hotter than the sun!',
  'HURNERJSGER?',
  'I have a suggestion.',
  'I miss ADOM!',
  'I need more context.',
  'I see your vocabulary has improved!',
  'idspispopd!',
  'if not ok then return end',
  'Indev!',
  'Indie!',
  'Information wants to be free!',
  'Ingots!',
  'Inspirational!',
  'Internet enabled!',
  'It came from space.',
  'It swings, it jives!',
  'Jag känner en bot!',
  'Jason! Jason! Jason!',
  'Java 16 + 1 = 17!',
  'Javalicious edition',
  'Jeb has amazing hair!',
  'Joel is neat!',
  'Jump up, jump up, and get down!',
  'Kaaneeeedaaaa!',
  'Keyboard compatible!',
  'Khaaaaaaaaan!',
  'Kick it root down!',
  'Kind of dragon free!',
  'Kinda like Lemmings!',
  'Kiss the sky!',
  'l33t!',
  'Larger than Earth!',
  'Learn about allyship!',
  'Legal in Finland!',
  'Lennart lennart = new Lennart();',
  'Less addictive than TV Tropes!',
  'Leveraging synergy!',
  'Limited edition!',
  'Lives in a pineapple under the sea!',
  'Livestreamed!',
  'Lots of truthiness!',
  'Loved by millions!',
  'Macroscopic!',
  'Made by "real" people!',
  'Made by Jeb!',
  'Made in Sweden!',
  'Made with lave!',
  'Make me a table, a funky table!',
  'MAP11 has two names!',
  'Matt Damon!',
  'May contain nuts!',
  'May contain traces of citrus!',
  'Meeting expectations!',
  'Menger sponge!',
  'Millions of peaches!',
  'Minecraft Java Edition presents: Disgusting Bugs',
  'Minecraft!',
  'Minors welcome!',
  'Mmmph, mmph!',
  'Moderately attractive!',
  'Monster infighting!',
  'More addictive than lemonade!',
  'More Digital!',
  'More polygons!',
  'More than 500 sold!',
  'Music by C418!',
  'Music by Lena Raine!',
  'My life for Aiur!',
  'Never dig down!',
  'Nice to meet you!',
  'Nooooooooooooo!',
  'Not as cool as Spock!',
  'Not linear!',
  'Not on Steam!',
  'Now contains 32 random daily cats!',
  'Now in 3D!',
  'Now on OpenGL 3.2 core profile!',
  'Now supports åäö!',
  'Now with additional stuff!',
  'Now with difficulty!',
  'Now with extra hugs!',
  'Now With Multiplayer!',
  'Now you are thinking with pistons!',
  'NP is not in P!',
  'Octagonal!',
  'Oh man!',
  'Oh, ok, Pigmen!',
  'OICU812!',
  'Omnipotent!',
  'One day, somewhere in the future, my work will be quoted!',
  'One of a kind!',
  'PC gaming since 1873!',
  'Peter Griffin!',
  'Ph1lza had a good run!',
  'Phobos anomaly!',
  'Ping the human!',
  'Pixels!',
  'Place ALL the blocks!',
  'Plant a tree!',
  'Plant-based light sources!',
  'Play him off, keyboard cat!',
  'Play Minecraft, Watch Topgear, Get Pig!',
  'Played by cowboys!',
  'pls rt',
  'Plz reply to my tweet!',
  'Pneumatic!',
  'Polynomial!',
  'Pretty scary!',
  'Pretty!',
  'Pumpa kungen!',
  'Pumpkinhead!',
  'Punching wood!',
  'Put a little fence around it!',
  'Put that cookie down!',
  'Rainbow turtle?',
  'Random splash!',
  'Read more books!',
  'Reference implementation!',
  'Regional resources!',
  'Replaced molten cheese with blood?',
  'Representing Edsbyn!',
  'Reticulating splines!',
  'RIBBIT!',
  'Ride the pig!',
  'Rise from your grave!',
  'Rita is the new top dog!',
  'Run, coward! I hunger!',
  'Ryan also has amazing hair!',
  'Save the world - stay inside!',
  'Scary!',
  'Scientific!',
  'See you next Friday or so!',
  'Seecret Friday update!',
  'Sensational!',
  'Shop for your elders!',
  'Should not be played while driving',
  'Shriek like a Sculk Shrieker!',
  'Singleplayer!',
  'Slow acting portals!',
  'So fresh, so clean!',
  'So sweet, like a nice bon bon!',
  'Soap and water!',
  'Something funny!',
  'Speak OUT against injustice and UP for equality!',
  'Spiders everywhere!',
  'sqrt(-1) love you!',
  'Stand up for equality in your community!',
  'Stay a while and listen!',
  'Stay a while, stay forever!',
  'Stay home and play games!',
  'Stay safe!',
  'Stay strong!',
  'Stop being reasonable, this is the Internet!',
  'Stop, hammertime!',
  'Strange, but not a stranger!',
  'Sublime!',
  'Supercalifragilisticexpialidocious!',
  'Support elderly relatives and friends!',
  'Support local businesses!',
  'Support the BIPOC community and creators!',
  'Survive!',
  'SWM forever!',
  'Swords for everyone!',
  'Synecdoche!',
  'Take an eggbeater and beat it against a skillet!',
  'Take frequent breaks!',
  'Take her pillow!',
  'Take the elevator to the mezzanine!',
  'Technically good!',
  'Technoblade never dies!',
  'Technologic!',
  'Teetsuuuuoooo!',
  'Tell your friends!',
  'Terrestrial!',
  'Testificates!',
  'Thank you for the fish!',
  'The creeper is a spy!',
  'The sky is the limit!',
  'The sum of its parts!',
  'The true meaning of covfefe',
  'Thematic!',
  'This is good for Realms.',
  'This is my true form!',
  'This parrot is no more! It has ceased to be!',
  'Thousands of colors!',
  'Throw a blanket over it!',
  'Throw yourself at the ground and miss',
  'Tip your waiter!',
  'Tougher than diamonds, rich like cream!',
  'Treatment for your rash!',
  'Truly gone fishing!',
  'Try it!',
  'Try the mushroom stew!',
  'Try the Nether!',
  'Turing complete!',
  'Twittered about!',
  'Tyrion would love it!',
  'Ultimate edition!',
  'umop-apisdn!',
  'Undefeated!',
  'Une baguette!',
  'Uninflammable!',
  'Uses LWJGL!',
  'Vanilla!',
  'Verlet intregration! [sic]',
  'Very fun!',
  'Very influential in its circle!',
  'Vote for net neutrality!',
  'Warning! A huge battleship "STEVE" is approaching fast!',
  'Wash your hands!',
  'Water bottle!',
  'Water proof!',
  'Welcome to your Doom!',
  'What do you expect?',
  'Where there is not light, there can spider!',
  'Who let the frogs out?',
  'Who put it there?',
  'Whoa, dude!',
  'Woah.',
  'Woo, 2pp!',
  'Woo, facepunch!',
  'Woo, reddit!',
  'Woo, somethingawful!',
  'Woo, tigsource!',
  'Woo, worldofminecraft!',
  'Wow!',
  'Yaaay!',
  'Yay, puppies for everyone!',
  'Yes, sir!',
  'You are valid!',
  'You are welcome here!',
  'Your gender is valid!',
  'Zoglin!?',
  'Γεια σου Ελλάδα!',
  '한국 안녕하세요!',
  '你好中国！',
  '日本ハロー！',
  "Any computer is a laptop if you're brave enough!",
  "Ceci n'est pas une title screen!",
  "Child's play!",
  "Consummate V's!",
  "Doesn't avoid double negatives!",
  "Doesn't use the U-word!",
  "Don't bother with the clones!",
  "Don't feed avocados to parrots!",
  "Don't feed chocolate to parrots!",
  "Don't look directly at the bugs!",
  "Don't touch your face!",
  "Don't worry, be happy!",
  "I'm glad you're here!",
  "In case it isn't obvious, foxes aren't players.",
  "It's a game!",
  "It's finished!",
  "It's groundbreaking!",
  "It's here!",
  "Let our battle's begin! [sic]",
  "Let's danec!",
  "Look mum, I'm in a splash!",
  "Prepare, but don't hoard!",
  "Rule #1: it's never my fault",
  "Something's not quite right...",
  "That's no moon!",
  "That's Numberwang!",
  "That's super!",
  "The bee's knees!",
  "The cutest predator you'll ever meet!",
  "There's <<a cat on ,my keyboard!~ [sic]",
  "There's no stopping the Trollmaso",
  "This message will never appear on the splash screen, isn't that weird?",
  "This text is hard to read if you play the game at the default resolution, but at 1080p it's fine!",
  "What's the question?",
  "What's up, Doc?",
  "You can't explain that!",
  "You're going too fast!",
  "You've got a brand new key!"
] as const

/**
 * 63 splashes from Minecraft Bedrock Edition
 */
export const be = [
  '!!!1!',
  '&amp; Knuckles!',
  '#Blessed!',
  '#gartzkebrokeit',
  '0% sugar!',
  '0xffff-1 chunks',
  '100% more yellow text!',
  'A circle-free environment!',
  'Alexander Hamilton!',
  'All blocks covered!',
  'Almost C++14!',
  'Artisinal!',
  'Ask your mother!',
  'Astronomically accurate!',
  'Bananas!',
  'Change my mind.',
  'Crush it!',
  'Cubism!',
  'Dramatic lighting!',
  'Endless!',
  'Episode 3!',
  'flowers more important than grass',
  'Funding secured!',
  'Glowing creepy eyes!',
  'Haha, LEL!',
  'Have you finished your homework?',
  'High-key!',
  'Hmmmrmm.',
  'Innovating innovation!',
  'Less polygons!',
  'Like that smash button!',
  'Living, breathing world!',
  'Llama, llama, duck!',
  'Machine learning!',
  'Made by Mojang!',
  'Made in C++!',
  'Make a viral video!!1',
  'Minecraft 2 unconfirmed!',
  'Mostly harmless!',
  'Multithreaded!',
  'Now with skins!',
  'Oh geez!',
  'OpenGL ES 2.0+!',
  'Pandamonium!',
  'Ported implementation!',
  'Potatoes gonna potate!',
  'Protec but also attac',
  'Quite Indie!',
  'Release the Snord!',
  'Savage Dad jokes!',
  'So. You read splash text.',
  'Sodium free!',
  'Take an egg beater and beat it against a skillet!',
  'Team Mystic!',
  'Thanks for the fish!',
  'The Floor is Lava!',
  'V-synched!',
  'What DOES the fox say?',
  'YANNY OR LAUREL???',
  'zhoolor',
  "Keep your head down, there's two of us in here now. Remember?",
  "We're working on it!",
  "When it's ready!"
] as const

/**
 * 502 splashes from Minecraft (Java + Bedrock)
 */
export const splashes = [...je, ...be] as const

export default splashes
